Added new posts and dog food article link
NUCSSA/nucssa-website pull request #19
Opened 2019-02-28 12:44 UTC by leyiqiang

2019-02-28 19:08 UTC, JJPro requested changes
这几个活动卡片的内容也添加到活动页面吧
`/content/pages/4--posts/index.md`
What do you think?

2019-03-01 15:15 UTC, JJPro approved these changes

2019-03-01 15:18 UTC, Haobo-Zhao reviewed
👍

2019-03-01 15:18 UTC, Haobo-Zhao approved these changes

2019-03-01 15:19 UTC, merged